FooTalent/Equipo-4

front/package-lock.json, front/package.json, front/tailwind.config.js
- **Actualización de dependencias**: Modificaciones en `package-lock.json` y `package.json` para abordar una alerta de vulnerabilidad de alta severidad.
- **Configuración de Tailwind**: Realización de una pequeña actualización en la configuración de Tailwind.
=> Fix vulnerabilities in dependencies

front/components.json, front/eslint.config.js, front/jsconfig.json, front/package-lock.json, front/package.json, front/src/components/ui/alert-dialog.jsx, front/src/components/ui/button.jsx, front/src/components/ui/dialog.jsx, front/src/components/ui/form.jsx, front/src/components/ui/index.js, front/src/components/ui/input.jsx, front/src/components/ui/label.jsx, front/src/components/ui/radio-group.jsx, front/src/index.css, front/src/lib/utils.js, front/tailwind.config.js, front/vite.config.js
[[FE]: Instalar todas las dependencias](https://github.com/FooTalent/Equipo-4/issues/5)
=> feat: instalar todas las dependencias del frontend 

front/src/modules/auth/admin/page.jsx, front/src/modules/auth/admin/personalize.jsx, front/src/modules/auth/admin/store.js, front/src/modules/auth/components/user-type.jsx, front/src/modules/auth/page.jsx, front/src/routes/index.jsx
=> fix: rutas de administrador 

front/src/modules/auth/admin/page.jsx, front/src/modules/auth/admin/personalize.jsx, front/src/modules/auth/components/user-type.jsx, front/src/modules/auth/family/page.jsx, front/src/modules/auth/family/personalize.jsx, front/src/modules/auth/page.jsx
=> feat(administrador): validación del formulario de ingreso

front/src/modules/auth/admin/personalize.jsx
=> feat(administrador): validación del formulario de personalizar credenciales

front/src/modules/auth/admin/personalize.jsx, front/src/modules/auth/family/page.jsx, front/src/modules/auth/family/personalize.jsx
=> feat(familia): validación de formularios de ingreso 

front/src/modules/auth/family/contrato-confidencialidad.jsx, front/src/modules/auth/family/personalize.jsx, front/src/modules/auth/family/terminos.jsx
=> fix(familia):  Corregir un error de validación

front/public/common/arrow-left.svg, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx
=> feat(UI/Móvil): dashboard del administrador

front/src/modules/dashboard/admin/components/admin-dashboard-desktop.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx, front/src/modules/dashboard/admin/pages/request-mentoring.jsx, front/src/routes/index.jsx
=> feat(UI): solicitud de mentorias  

front/src/modules/dashboard/admin/components/admin-dashboard-desktop.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx, front/src/modules/dashboard/admin/pages/profile.jsx, front/src/modules/dashboard/admin/pages/request-mentoring.jsx, front/src/modules/dashboard/admin/pages/volunteer-families.jsx, front/src/routes/index.jsx
=> feat(UI): familias voluntarias 

front/public/dashboard-admin/minus-square.svg, front/src/modules/dashboard/admin/components/admin-dashboard-desktop.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx, front/src/modules/dashboard/admin/pages/follow-up-families.jsx, front/src/routes/index.jsx
=> feat(UI): seguimiento de familias

front/index.html, front/public/favicon.svg
=> fix: título e icono de la aplicación

front/package-lock.json, front/package.json, front/src/components/ui/index.js, front/src/components/ui/select.jsx, front/src/components/ui/textarea.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-desktop.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx, front/src/modules/dashboard/admin/pages/general-email.jsx, front/src/routes/index.jsx
=> feat(UI): email general

front/src/components/ui/dialog.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-desktop.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx, front/src/modules/dashboard/admin/components/create-user.jsx, front/src/routes/index.jsx
=> feat(UI): crear un nuevo usuario 

front/src/layouts/app-layout.jsx, front/src/modules/auth/admin/api/index.js, front/src/modules/auth/admin/page.jsx, front/src/modules/auth/admin/personalize.jsx, front/src/modules/auth/page.jsx, front/src/store/user.js
=> feat(administrador): primer ingreso

front/src/modules/auth/admin/personalize.jsx
=> fix(administrador): cerrar sesión 

front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/components/create-user.jsx, front/src/modules/dashboard/admin/schemas/schemaCreateUser.js
=> feat: crear un nuevo usuario 

front/src/modules/dashboard/admin/components/create-user.jsx, front/src/modules/dashboard/admin/schemas/schemaCreateUser.js
=> feat: tipo de usuario en el formulario de crear usuario 

front/src/components/ui/select.jsx, front/src/modules/dashboard/admin/components/create-user.jsx
=> feat: borrar el rol de usuario en crear usuario 

front/src/components/ui/index.js, front/src/components/ui/pagination.jsx, front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/components/familia.jsx, front/src/modules/dashboard/admin/pages/list-families.jsx
=> feat: listado de familias 

front/public/common/read.svg, front/public/common/tick-square.svg, front/src/components/shared/footer.jsx, front/src/components/shared/navbar.jsx, front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/components/notification.jsx, front/src/modules/dashboard/admin/pages/notifications.jsx, front/src/routes/index.jsx
=> feat: notificaciones de usuario administrador 

front/src/modules/auth/admin/page.jsx, front/src/modules/auth/family/api/familyAuthApi.js, front/src/modules/auth/family/olvidar-contrasena.jsx, front/src/modules/auth/page.jsx, front/src/routes/index.jsx
=> feat: ingreso unico 

front/src/modules/auth/family/recuperar-contrasena.jsx, front/src/routes/index.jsx
=> feat: recuperar la contraseña 

front/src/modules/auth/admin/page.jsx, front/src/modules/auth/admin/personalize.jsx, front/src/modules/auth/components/user-type.jsx, front/src/modules/auth/family/contrato-confidencialidad.jsx, front/src/modules/auth/family/olvidar-contrasena.jsx, front/src/modules/auth/family/personalize.jsx, front/src/modules/auth/family/recuperar-contrasena.jsx, front/src/modules/auth/family/terminos.jsx, front/src/modules/auth/login/page.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-desktop.jsx, front/src/modules/dashboard/admin/components/admin-dashboard-mobile.jsx, front/src/modules/dashboard/admin/components/create-user.jsx, front/src/modules/dashboard/admin/page.jsx, front/src/modules/dashboard/admin/pages/follow-up-families.jsx, front/src/modules/dashboard/admin/pages/general-email.jsx, front/src/modules/dashboard/admin/pages/list-families.jsx, front/src/modules/dashboard/admin/pages/notifications.jsx, front/src/modules/dashboard/admin/pages/profile.jsx, front/src/modules/dashboard/admin/pages/request-mentoring.jsx, front/src/modules/dashboard/admin/pages/volunteer-families.jsx, front/tailwind.config.js
=> fix: cambiar los colores principales de la app

README.md, front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/pages/request-mentoring.jsx, front/src/modules/dashboard/admin/pages/volunteer-families.jsx, front/src/routes/index.jsx
=> feat: familias voluntarias + README 

front/src/components/ui/button.jsx, front/src/modules/auth/family/HomeFamilies.jsx, front/src/modules/auth/family/contrato-confidencialidad.jsx, front/src/modules/auth/family/olvidar-contrasena.jsx, front/src/modules/auth/family/recuperar-contrasena.jsx, front/src/modules/auth/family/terminos.jsx, front/src/modules/auth/login/page.jsx, front/src/modules/auth/page.jsx, front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/components/create-user.jsx, front/src/modules/dashboard/admin/components/familia.jsx, front/src/modules/dashboard/admin/pages/follow-up-families.jsx, front/src/modules/dashboard/admin/pages/list-families.jsx, front/src/modules/dashboard/admin/pages/notifications.jsx, front/src/modules/dashboard/admin/pages/profile.jsx, front/src/modules/dashboard/admin/pages/request-mentoring.jsx, front/src/modules/dashboard/admin/pages/volunteer-families.jsx, front/tailwind.config.js
=> style: actualizar los botones

front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/pages/list-families.jsx
=> feat: buscador de familias 

front/src/modules/dashboard/admin/pages/general-email.jsx
=> Correción general email

front/src/modules/auth/family/HomeFamilies.jsx, front/src/modules/auth/family/contrato-confidencialidad.jsx, front/src/modules/auth/family/personalize.jsx, front/src/modules/auth/family/terminos.jsx, front/src/modules/auth/login/page.jsx, front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/pages/general-email.jsx, front/src/modules/dashboard/admin/pages/list-families.jsx
=> fix: stilos de css y la logica del primer ingreso de familias 

front/src/components/shared/navbar.jsx
=> feat: modal de cerrar sesión 

front/src/modules/dashboard/admin/components/create-user.jsx, front/src/modules/dashboard/admin/schemas/schemaCreateUser.js
=> feat: cargo del nuevo usuario administrador 

front/src/modules/dashboard/admin/pages/profile.jsx
=> fix: eliminar cambiar el correo 

front/src/components/shared/footer.jsx, front/src/modules/dashboard/admin/page.jsx
=> feat: proteger las rutas de administrador 

front/src/modules/dashboard/admin/pages/general-email.jsx
Ajustes en la vista email general
=> Cambios email general

front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/pages/general-email.jsx
Se ejecuta yarn build para que se reflejn los cambios
=> Yarn build para reflejar los cambios en la web

front/src/modules/auth/family/api/createFamily.js, front/src/modules/dashboard/admin/api/index.js, front/src/modules/dashboard/admin/pages/family-profile.jsx, front/src/modules/dashboard/admin/pages/mentoringRequest/components/FamilyCard.jsx, front/src/modules/dashboard/admin/pages/volunteer-families.jsx
=> fix: removed all console logs

front/src/modules/dashboard/admin/components/create-user.jsx
=> fix: crear un nuevo usuario 

front/src/modules/auth/login/page.jsx
=> feat: nuevo inicio de sesión 
